### ISSUE TITLE
pieceEntry and pawnEntry aren't re-allocated if `tb_init` is called after `tb_free`

### ISSUE THREAD

**Issue by Algorhythm-sxv** [AndyGrant/Pyrrhic#6]
The code for `tb_init` checks `if !pieceEntry` when called with a path to initialize with, but when `tb_free` is called, this pointer is not reset to `NULL`. Therefore if `tb_init` is called, then `tb_free` (which `free`s `pieceEntry` and `pawnEntry`), then `tb_init` again, these arrays will not be reallocated and will cause an out-of-bounds memory access.

The fix is seemingly rather simple, just set `pieceEntry = NULL; pawnEntry = NULL;` in `tb_free` after the contents are freed.

**Comment by kmar** [comment]
bite me as well recently, your fix seems wrong though? you should clear pieceEntry and pawnEntry to NULL in tb_free instead

**Comment by Algorhythm-sxv** [comment]
@kmar is that not what what I am doing? There are two commits in the PR if you missed the last one. The pointers are set to null in `tb_free` immediately after being `free`d

**Comment by kmar** [comment]
ah yes, I see, the second commit fixes the first one, one commit would be nicer though :)

**Comment by AndyGrant** [comment]
Thanks. Merged via https://github.com/AndyGrant/Pyrrhic/commit/c88405c01452f906a6f7808f5b22d3679138016b
